name: 'Build dependency package locally'
description: 'Checks out a dependency package locally and updates all references to it'
inputs:
  package:
    description: 'Name of the package'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Clone
      uses: actions/checkout@v3
      with:
        repository: cloudscape-design/${{ inputs.package }}
        path: ${{ inputs.package }}
    - name: Build
      uses: ${{ inputs.package }}/.github/workflows/build-lint-test.yml
      env:
        AWSUI_DRY_RUN: 'true'
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.package }}
        path: '*.tgz'
