name: 'Create a Release'
description: 'Create a release for a tag'
inputs:
  tag_name:
    description: 'The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag'
    required: true
  release_name:
    description: 'The name of the release. For example, `Release v1.0.1`'
    required: true
  body_path:
    description: 'Path to file with information about the tag.'
    required: false
  commitish:
    description: 'Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists. Default: SHA of current commit'
    required: false
outputs:
  id:
    description: 'The ID of the created Release'
  html_url:
    description: 'The URL users can navigate to in order to view the release'
  upload_url:
    description: 'The URL for uploading assets to the release'

runs:
  using: 'node16'
  main: 'create-release.mjs'