name: Lint PR

on:
  pull_request:

permissions: {}

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    env:
      TITLE: ${{ github.event.pull_request.title }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const title = process.env.TITLE;

            const allowedTypes = ["chore", "feat", "fix", "refactor", "test", "revert"];

            const matchesType = allowedTypes.some( type => title.startsWith(type + ":") );

            if(!matchesType) {
              console.log('PR title does follow the convention "type: subject". Allowed types are:', allowedTypes.join(", "))
              console.log("This PR's title is:", title)
              process.exitCode = 1;
            }
