name: Lint PR

on:
  workflow_call:

permissions: {}

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    env:
      TITLE: ${{ github.event.pull_request.title }}
    steps:
      - run: |
          if [[ "$TITLE" =~ (^(chore|feat|fix|refactor|test|revert){1}?: ([[:alnum:]])+([[:space:][:print:]]*)) ]]; then
           echo "Valid PR title"
          else 
           echo 'PR title does not follow the convention "type: subject"'
           echo 'type must be one of the following: feat|fix|chore|refactor|test|revert'
           exit 1
          fi
        shell: bash
