name: Lint PR

on:
  workflow_call:

permissions: {}

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    env:
      TITLE: ${{ github.event.pull_request.title }}
    steps:
      - run: |
          import os, re
          valid_types = ['chore', 'feat', 'fix', 'refactor', 'test', 'revert']
          try:
              segments = re.split(r':\s*', title, maxsplit=1)
              if (len(segments) != 2):
                  raise Exception('PR title does not follow "type: subject" convention')
              type, subject = segments
              if type.lower() not in valid_types:
                  raise Exception('Invalid commit type')
              if not all(c.isprintable() for c in subject):
                  raise Exception('Invalid commit subject')
              print('PR title is valid')
              exit(0)
          except Exception as e:
              print('Error: {}'.format(e.args[0]))
              print('PR title does not follow the convention "type: subject"\nValid types are: {}'.format(', '.join(valid_types)))
              exit(1)
        shell: python
